version: '3'

tasks:
  abigen:
    cmds:
      - cd contract; rm AvaLido.go; rm MpcManager.go; go generate
    silent: false
  setAvaLidoAddr:
    cmds:
      - cast send --rpc-url http://127.0.0.1:9650/ext/bc/C/rpc --from 0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC --private-key 56289e99c94b6912bfc12adc093c9b51124f0dc54ac7a766b2bc5ccf558d8027 $MPC_MANAGER "setAvaLidoAddress(address)" $AVALIDO
    silent: false
  fund:
    cmds:
      - cast send --rpc-url http://127.0.0.1:9650/ext/bc/C/rpc --from 0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC --private-key 56289e99c94b6912bfc12adc093c9b51124f0dc54ac7a766b2bc5ccf558d8027 --value 100ether  {{.CLI_ARGS}}
    silent: false
  balance:
    cmds:
      - cast balance {{.CLI_ARGS}}  --rpc-url http://127.0.0.1:9650/ext/bc/C/rpc
    silent: false
  strlen:
    cmds:
      - string={{.CLI_ARGS}}; echo ${#string}
    silent: false
  lastaddr:
    cmds:
      - cast call --rpc-url http://127.0.0.1:9650/ext/bc/C/rpc  {{.CLI_ARGS}} "lastGenAddress()"
    silent: false
  requestStake:
    cmds:
      - cast send --rpc-url http://127.0.0.1:9650/ext/bc/C/rpc --from 0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC --private-key 56289e99c94b6912bfc12adc093c9b51124f0dc54ac7a766b2bc5ccf558d8027 --value 1ether {{.CLI_ARGS}}  "requestStake(string,uint256,uint256,uint256)" "NodeID-P7oB2McjBGgW2NXXWVYjV8JEDFoW9xDE5" 1ether 1 2
    silent: false

