version: '3'

tasks:
  fund:
    cmds:
      - cast send --rpc-url http://127.0.0.1:9650/ext/bc/C/rpc --from 0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC --private-key 56289e99c94b6912bfc12adc093c9b51124f0dc54ac7a766b2bc5ccf558d8027 --value 100ether  {{.CLI_ARGS}}
    silent: false
  balance:
    cmds:
      - cast balance {{.CLI_ARGS}}  --rpc-url http://127.0.0.1:9650/ext/bc/C/rpc
    silent: false
  strlen:
    cmds:
      - string={{.CLI_ARGS}}; echo ${#string}
    silent: false