enableDevMode: true
controllerId: "mpc-controller-02"
controllerKey: "6c326909bee727d5fc434e2c75a3e0126df2ec4f49ad02cdd6209cf19f91da33"
coordinatorAddress: "0x80D72Ef553C7B5f92f6966c2799d926d26Da3dAF"
mpcServerUrl: "http://localhost:8002"
ethRpcUrl: "http://localhost:9650/ext/bc/C/rpc"
ethWsUrl: "ws://127.0.0.1:9650/ext/bc/C/ws"
cChainIssueUrl: "http://localhost:9650"
pChainIssueUrl: "http://localhost:9650"
confignetwork:
  networkId: 12345
  chainId: 43112
  cChainId: "2CA6j5zYzasynPsFeNoqWkmTCt3VScMvXUZHbfDJ8k3oGzAPtU"
  avaxId: "2fombhL7aGPwj3KH4bfrmJwW6PVnMobf9Y2fn9GwxiAAJyFDbe"
  importFee: 1000000
  gasPerByte: 1
  gasPerSig: 1000
  gasFixed: 10000
configdbbadger:
  badgerDbPath: "./mpc_controller_db2"
