// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	evm "github.com/ava-labs/coreth/plugin/evm"
	mock "github.com/stretchr/testify/mock"

	platformvm "github.com/ava-labs/avalanchego/vms/platformvm"
)

// SignedTxGetter is an autogenerated mock type for the SignedTxGetter type
type SignedTxGetter struct {
	mock.Mock
}

// GetSignedAddDelegatorTx provides a mock function with given fields:
func (_m *SignedTxGetter) GetSignedAddDelegatorTx() (*platformvm.Tx, error) {
	ret := _m.Called()

	var r0 *platformvm.Tx
	if rf, ok := ret.Get(0).(func() *platformvm.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platformvm.Tx)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSignedExportTx provides a mock function with given fields:
func (_m *SignedTxGetter) GetSignedExportTx() (*evm.Tx, error) {
	ret := _m.Called()

	var r0 *evm.Tx
	if rf, ok := ret.Get(0).(func() *evm.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*evm.Tx)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSignedImportTx provides a mock function with given fields:
func (_m *SignedTxGetter) GetSignedImportTx() (*platformvm.Tx, error) {
	ret := _m.Called()

	var r0 *platformvm.Tx
	if rf, ok := ret.Get(0).(func() *platformvm.Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*platformvm.Tx)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewSignedTxGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewSignedTxGetter creates a new instance of SignedTxGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSignedTxGetter(t mockConstructorTestingTNewSignedTxGetter) *SignedTxGetter {
	mock := &SignedTxGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
