// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	staking "github.com/avalido/mpc-controller/tasks/staking"
	mock "github.com/stretchr/testify/mock"
)

// StakeTaskerCreatorer is an autogenerated mock type for the StakeTaskerCreatorer type
type StakeTaskerCreatorer struct {
	mock.Mock
}

// CreateStakeTask provides a mock function with given fields:
func (_m *StakeTaskerCreatorer) CreateStakeTask() (staking.StakeTasker, error) {
	ret := _m.Called()

	var r0 staking.StakeTasker
	if rf, ok := ret.Get(0).(func() staking.StakeTasker); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(staking.StakeTasker)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStakeTaskerCreatorer interface {
	mock.TestingT
	Cleanup(func())
}

// NewStakeTaskerCreatorer creates a new instance of StakeTaskerCreatorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStakeTaskerCreatorer(t mockConstructorTestingTNewStakeTaskerCreatorer) *StakeTaskerCreatorer {
	mock := &StakeTaskerCreatorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
