// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	ids "github.com/ava-labs/avalanchego/ids"
	mock "github.com/stretchr/testify/mock"
)

// TxIssuer is an autogenerated mock type for the TxIssuer type
type TxIssuer struct {
	mock.Mock
}

// IssueExportTx provides a mock function with given fields: ctx, exportTxBytes
func (_m *TxIssuer) IssueExportTx(ctx context.Context, exportTxBytes []byte) (ids.ID, error) {
	ret := _m.Called(ctx, exportTxBytes)

	var r0 ids.ID
	if rf, ok := ret.Get(0).(func(context.Context, []byte) ids.ID); ok {
		r0 = rf(ctx, exportTxBytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ids.ID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, exportTxBytes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IssueImportTx provides a mock function with given fields: ctx, importTxBytes
func (_m *TxIssuer) IssueImportTx(ctx context.Context, importTxBytes []byte) (ids.ID, error) {
	ret := _m.Called(ctx, importTxBytes)

	var r0 ids.ID
	if rf, ok := ret.Get(0).(func(context.Context, []byte) ids.ID); ok {
		r0 = rf(ctx, importTxBytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ids.ID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, importTxBytes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTxIssuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewTxIssuer creates a new instance of TxIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTxIssuer(t mockConstructorTestingTNewTxIssuer) *TxIssuer {
	mock := &TxIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
