package events

import "github.com/avalido/mpc-controller/contract"

// ---------------------------------------------------------------------------------------------------------------------
// Events originally generated by MpcManager smart contract

type EvtFromMpcManagerParticipantAdded struct {
	Evt *contract.MpcManagerParticipantAdded
}

type EvtFromMpcManagerKeygenRequestAdded struct {
	Evt *contract.MpcManagerKeygenRequestAdded
}

type EvtFromMpcManagerKeyGenerated struct {
	Evt *contract.MpcManagerKeyGenerated
}

type EvtFromMpcManagerStakeRequestAdded struct {
	Evt *contract.MpcManagerStakeRequestAdded
}

type EvtFromMpcManagerStakeRequestStarted struct {
	Evt *contract.MpcManagerStakeRequestStarted
}

type EvtFromMpcManagerSignRequestAdded struct {
	Evt *contract.MpcManagerSignRequestAdded
}

type EvtFromMpcManagerSignRequestStarted struct {
	Evt *contract.MpcManagerSignRequestStarted
}
